[Search]
# Characters that denote a phrase boundary. Anchors will not cross these characters.
separator_chars = . , : ; ? ! —

# Number of words to use for the start/end anchors.
anchor_length = 4
verify_content = true

